name: flutter_throttle_debounce
description: A comprehensive debouncing and throttling utility for search, API calls, and user interactions in Flutter applications.
version: 0.0.1
homepage: https://pub.dev/packages/flutter_throttle_debounce
repository: https://github.com/Dhia-Bechattaoui/flutter_throttle_debounce
issue_tracker: https://github.com/Dhia-Bechattaoui/flutter_throttle_debounce/issues
documentation: https://pub.dev/documentation/flutter_throttle_debounce/latest/

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: ^1.0.0

topics:
  - debounce
  - throttle
  - performance
  - search
  - api
  - utilities

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

funding:
  - https://github.com/sponsors/Dhia-Bechattaoui
